<?php
/** Cancellation barriers prevent new charges and permit only read-only reconciliation. */
use PHPUnit\Framework\TestCase;
use PHPUnit\Util\PHP\AbstractPhpProcess;
final class StripeCancellationRaceTest extends TestCase {
 private function fixture():array{$path=dirname(__DIR__).'/fixtures/run-stripe-cancellation-race.php';$output=AbstractPhpProcess::factory()->runJob('<?php require '.var_export($path,true).';');self::assertSame('',$output['stderr']);$data=json_decode($output['stdout'],true);self::assertIsArray($data,$output['stdout']);return $data;}
 public function test_already_cancelled_dispatch_stops_before_provider_preparation():void{$case=$this->fixture()['already_cancelled'];self::assertNull($case['error']);self::assertSame(0,$case['prepare']);self::assertSame(0,$case['dispatches']);self::assertSame('cancellation_barrier',$case['response_code']);self::assertSame($case['locks'],$case['unlocks']);}
 public function test_cancellation_during_preparation_stops_before_provider_charge_and_unlocks():void{$case=$this->fixture()['before_dispatch'];self::assertNull($case['error']);self::assertSame(0,$case['dispatches']);self::assertSame('cancellation_barrier',$case['response_code']);self::assertSame($case['locks'],$case['unlocks']);self::assertSame($case['order_locks'],$case['order_unlocks']);self::assertNotEmpty($case['events']);}
 public function test_cancelled_retry_only_reads_prior_intent_and_records_review():void{$d=$this->fixture();foreach(array('reconcile','reconcile_error') as $name){$case=$d[$name];self::assertNull($case['error']);self::assertSame(0,$case['dispatches']);self::assertSame(array('payment_intents/pi_offline'),$case['reads']);self::assertSame(0,$case['prepare']);self::assertNotEmpty($case['events']);self::assertSame('dispatch_review',$case['events'][0]['event_type']);}}
 public function test_cancellation_after_dispatch_records_review_without_another_charge():void{$case=$this->fixture()['during_dispatch'];self::assertNull($case['error']);self::assertSame(1,$case['dispatches']);self::assertSame('cancellation_review',$case['response_code']);self::assertSame($case['locks'],$case['unlocks']);self::assertSame($case['order_locks'],$case['order_unlocks']);self::assertSame('dispatch_review',$case['events'][0]['event_type']);}
}
